name: Build My App
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Build our app
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: List
        run: ls
      - name: Check DotnetCli
        run: dotnet
      - name: Check NPM
        run: npm