name: Build My App
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Build our app
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
#      - name: Hello world
#        uses: actions/hello-world-javascript-action@v1
#        with:
#          who-to-greet: 'Mona the Octocat'
#        id: hello
      - name: List
        run: ls
